// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes(in *jlexer.Lexer, out *SendReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "sends":
			if in.IsNull() {
				in.Skip()
				out.Sends = nil
			} else {
				in.Delim('[')
				if out.Sends == nil {
					if !in.IsDelim(']') {
						out.Sends = make([]*Send, 0, 8)
					} else {
						out.Sends = []*Send{}
					}
				} else {
					out.Sends = (out.Sends)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *Send
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Send)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Sends = append(out.Sends, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes(out *jwriter.Writer, in SendReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sends\":"
		out.RawString(prefix[1:])
		if in.Sends == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Sends {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SendReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SendReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SendReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SendReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes(l, v)
}
func easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes1(in *jlexer.Lexer, out *Send) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "to":
			if in.IsNull() {
				in.Skip()
				out.To = nil
			} else {
				out.To = in.Bytes()
			}
		case "amount":
			out.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes1(out *jwriter.Writer, in Send) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix[1:])
		out.Base64Bytes(in.To)
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Amount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Send) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Send) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Send) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Send) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes1(l, v)
}
func easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes2(in *jlexer.Lexer, out *MintReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "supply":
			out.Supply = uint64(in.Uint64())
		case "lock":
			if in.IsNull() {
				in.Skip()
				out.Lock = nil
			} else {
				out.Lock = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes2(out *jwriter.Writer, in MintReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"supply\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Supply))
	}
	{
		const prefix string = ",\"lock\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Lock)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MintReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MintReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComFyxgamingVmTokenTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MintReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MintReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComFyxgamingVmTokenTypes2(l, v)
}
