// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComFyxgamingVmXpTypes(in *jlexer.Lexer, out *BattleReceipt) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fighter":
			if in.IsNull() {
				in.Skip()
				out.Fighter = nil
			} else {
				out.Fighter = in.Bytes()
			}
		case "xp":
			out.Xp = int32(in.Int32())
		case "lock":
			if in.IsNull() {
				in.Skip()
				out.Lock = nil
			} else {
				out.Lock = in.Bytes()
			}
		case "win":
			out.Win = bool(in.Bool())
		case "pvp":
			out.PvP = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComFyxgamingVmXpTypes(out *jwriter.Writer, in BattleReceipt) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fighter\":"
		out.RawString(prefix[1:])
		out.Base64Bytes(in.Fighter)
	}
	{
		const prefix string = ",\"xp\":"
		out.RawString(prefix)
		out.Int32(int32(in.Xp))
	}
	{
		const prefix string = ",\"lock\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Lock)
	}
	{
		const prefix string = ",\"win\":"
		out.RawString(prefix)
		out.Bool(bool(in.Win))
	}
	{
		const prefix string = ",\"pvp\":"
		out.RawString(prefix)
		out.Bool(bool(in.PvP))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BattleReceipt) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComFyxgamingVmXpTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BattleReceipt) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComFyxgamingVmXpTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BattleReceipt) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComFyxgamingVmXpTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BattleReceipt) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComFyxgamingVmXpTypes(l, v)
}
