// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package lib

import (
	json "encoding/json"
	bscript "github.com/libsv/go-bt/v2/bscript"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE910b2f5DecodeGithubComFyxgamingVmLib(in *jlexer.Lexer, out *ExecContext) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "action":
			out.Action = Action(in.Uint8())
		case "contract":
			if in.IsNull() {
				in.Skip()
				out.Contract = nil
			} else {
				if out.Contract == nil {
					out.Contract = new(Outpoint)
				}
				if in.IsNull() {
					in.Skip()
					*out.Contract = nil
				} else {
					*out.Contract = in.Bytes()
				}
			}
		case "method":
			out.Method = string(in.String())
		case "callData":
			if in.IsNull() {
				in.Skip()
				out.CallData = nil
			} else {
				out.CallData = in.Bytes()
			}
		case "stack":
			if in.IsNull() {
				in.Skip()
				out.Stack = nil
			} else {
				in.Delim('[')
				if out.Stack == nil {
					if !in.IsDelim(']') {
						out.Stack = make([]*ExecContext, 0, 8)
					} else {
						out.Stack = []*ExecContext{}
					}
				} else {
					out.Stack = (out.Stack)[:0]
				}
				for !in.IsDelim(']') {
					var v3 *ExecContext
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						if v3 == nil {
							v3 = new(ExecContext)
						}
						(*v3).UnmarshalEasyJSON(in)
					}
					out.Stack = append(out.Stack, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "parent":
			out.Parent = int32(in.Int32())
		case "instance":
			if in.IsNull() {
				in.Skip()
				out.Instance = nil
			} else {
				if out.Instance == nil {
					out.Instance = new(Instance)
				}
				easyjsonE910b2f5DecodeGithubComFyxgamingVmLib1(in, out.Instance)
			}
		case "events":
			if in.IsNull() {
				in.Skip()
				out.Events = nil
			} else {
				in.Delim('[')
				if out.Events == nil {
					if !in.IsDelim(']') {
						out.Events = make([]*Event, 0, 8)
					} else {
						out.Events = []*Event{}
					}
				} else {
					out.Events = (out.Events)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *Event
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(Event)
						}
						easyjsonE910b2f5DecodeGithubComFyxgamingVmLib2(in, v4)
					}
					out.Events = append(out.Events, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "children":
			if in.IsNull() {
				in.Skip()
				out.Children = nil
			} else {
				in.Delim('[')
				if out.Children == nil {
					if !in.IsDelim(']') {
						out.Children = make([]*Child, 0, 8)
					} else {
						out.Children = []*Child{}
					}
				} else {
					out.Children = (out.Children)[:0]
				}
				for !in.IsDelim(']') {
					var v5 *Child
					if in.IsNull() {
						in.Skip()
						v5 = nil
					} else {
						if v5 == nil {
							v5 = new(Child)
						}
						easyjsonE910b2f5DecodeGithubComFyxgamingVmLib3(in, v5)
					}
					out.Children = append(out.Children, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE910b2f5EncodeGithubComFyxgamingVmLib(out *jwriter.Writer, in ExecContext) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"action\":"
		out.RawString(prefix[1:])
		out.Uint8(uint8(in.Action))
	}
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix)
		if in.Contract == nil {
			out.RawString("null")
		} else {
			out.Base64Bytes(*in.Contract)
		}
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	if len(in.CallData) != 0 {
		const prefix string = ",\"callData\":"
		out.RawString(prefix)
		out.Base64Bytes(in.CallData)
	}
	if len(in.Stack) != 0 {
		const prefix string = ",\"stack\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v10, v11 := range in.Stack {
				if v10 > 0 {
					out.RawByte(',')
				}
				if v11 == nil {
					out.RawString("null")
				} else {
					(*v11).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"parent\":"
		out.RawString(prefix)
		out.Int32(int32(in.Parent))
	}
	{
		const prefix string = ",\"instance\":"
		out.RawString(prefix)
		if in.Instance == nil {
			out.RawString("null")
		} else {
			easyjsonE910b2f5EncodeGithubComFyxgamingVmLib1(out, *in.Instance)
		}
	}
	if len(in.Events) != 0 {
		const prefix string = ",\"events\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v12, v13 := range in.Events {
				if v12 > 0 {
					out.RawByte(',')
				}
				if v13 == nil {
					out.RawString("null")
				} else {
					easyjsonE910b2f5EncodeGithubComFyxgamingVmLib2(out, *v13)
				}
			}
			out.RawByte(']')
		}
	}
	if len(in.Children) != 0 {
		const prefix string = ",\"children\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v14, v15 := range in.Children {
				if v14 > 0 {
					out.RawByte(',')
				}
				if v15 == nil {
					out.RawString("null")
				} else {
					easyjsonE910b2f5EncodeGithubComFyxgamingVmLib3(out, *v15)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExecContext) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE910b2f5EncodeGithubComFyxgamingVmLib(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExecContext) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE910b2f5EncodeGithubComFyxgamingVmLib(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExecContext) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE910b2f5DecodeGithubComFyxgamingVmLib(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExecContext) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE910b2f5DecodeGithubComFyxgamingVmLib(l, v)
}
func easyjsonE910b2f5DecodeGithubComFyxgamingVmLib3(in *jlexer.Lexer, out *Child) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "contract":
			if in.IsNull() {
				in.Skip()
				out.Contract = nil
			} else {
				if out.Contract == nil {
					out.Contract = new(Outpoint)
				}
				if in.IsNull() {
					in.Skip()
					*out.Contract = nil
				} else {
					*out.Contract = in.Bytes()
				}
			}
		case "method":
			out.Method = string(in.String())
		case "callData":
			if in.IsNull() {
				in.Skip()
				out.CallData = nil
			} else {
				out.CallData = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE910b2f5EncodeGithubComFyxgamingVmLib3(out *jwriter.Writer, in Child) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix[1:])
		if in.Contract == nil {
			out.RawString("null")
		} else {
			out.Base64Bytes(*in.Contract)
		}
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"callData\":"
		out.RawString(prefix)
		out.Base64Bytes(in.CallData)
	}
	out.RawByte('}')
}
func easyjsonE910b2f5DecodeGithubComFyxgamingVmLib2(in *jlexer.Lexer, out *Event) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "topics":
			if in.IsNull() {
				in.Skip()
				out.Topics = nil
			} else {
				in.Delim('[')
				if out.Topics == nil {
					if !in.IsDelim(']') {
						out.Topics = make([][]uint8, 0, 2)
					} else {
						out.Topics = [][]uint8{}
					}
				} else {
					out.Topics = (out.Topics)[:0]
				}
				for !in.IsDelim(']') {
					var v22 []uint8
					if in.IsNull() {
						in.Skip()
						v22 = nil
					} else {
						v22 = in.Bytes()
					}
					out.Topics = append(out.Topics, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE910b2f5EncodeGithubComFyxgamingVmLib2(out *jwriter.Writer, in Event) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"topics\":"
		out.RawString(prefix)
		if in.Topics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v24, v25 := range in.Topics {
				if v24 > 0 {
					out.RawByte(',')
				}
				out.Base64Bytes(v25)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjsonE910b2f5DecodeGithubComFyxgamingVmLib1(in *jlexer.Lexer, out *Instance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "txo":
			if in.IsNull() {
				in.Skip()
				out.Txo = nil
			} else {
				if out.Txo == nil {
					out.Txo = new(Txo)
				}
				easyjsonE910b2f5DecodeGithubComFyxgamingVmLib4(in, out.Txo)
			}
		case "outpoint":
			if in.IsNull() {
				in.Skip()
				out.Outpoint = nil
			} else {
				if out.Outpoint == nil {
					out.Outpoint = new(Outpoint)
				}
				if in.IsNull() {
					in.Skip()
					*out.Outpoint = nil
				} else {
					*out.Outpoint = in.Bytes()
				}
			}
		case "origin":
			if in.IsNull() {
				in.Skip()
				out.Origin = nil
			} else {
				if out.Origin == nil {
					out.Origin = new(Outpoint)
				}
				if in.IsNull() {
					in.Skip()
					*out.Origin = nil
				} else {
					*out.Origin = in.Bytes()
				}
			}
		case "nonce":
			out.Nonce = uint64(in.Uint64())
		case "kind":
			if in.IsNull() {
				in.Skip()
				out.Kind = nil
			} else {
				if out.Kind == nil {
					out.Kind = new(Outpoint)
				}
				if in.IsNull() {
					in.Skip()
					*out.Kind = nil
				} else {
					*out.Kind = in.Bytes()
				}
			}
		case "sats":
			out.Satoshis = uint64(in.Uint64())
		case "lock":
			if in.IsNull() {
				in.Skip()
				out.Lock = nil
			} else {
				out.Lock = in.Bytes()
			}
		case "store":
			if in.IsNull() {
				in.Skip()
				out.Storage = nil
			} else {
				out.Storage = in.Bytes()
			}
		case "code":
			if in.IsNull() {
				in.Skip()
				out.Code = nil
			} else {
				out.Code = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE910b2f5EncodeGithubComFyxgamingVmLib1(out *jwriter.Writer, in Instance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txo\":"
		out.RawString(prefix[1:])
		if in.Txo == nil {
			out.RawString("null")
		} else {
			easyjsonE910b2f5EncodeGithubComFyxgamingVmLib4(out, *in.Txo)
		}
	}
	if in.Outpoint != nil {
		const prefix string = ",\"outpoint\":"
		out.RawString(prefix)
		out.Base64Bytes(*in.Outpoint)
	}
	if in.Origin != nil {
		const prefix string = ",\"origin\":"
		out.RawString(prefix)
		out.Base64Bytes(*in.Origin)
	}
	if in.Nonce != 0 {
		const prefix string = ",\"nonce\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Nonce))
	}
	if in.Kind != nil {
		const prefix string = ",\"kind\":"
		out.RawString(prefix)
		out.Base64Bytes(*in.Kind)
	}
	{
		const prefix string = ",\"sats\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Satoshis))
	}
	{
		const prefix string = ",\"lock\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Lock)
	}
	if len(in.Storage) != 0 {
		const prefix string = ",\"store\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Storage)
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Code)
	}
	out.RawByte('}')
}
func easyjsonE910b2f5DecodeGithubComFyxgamingVmLib4(in *jlexer.Lexer, out *Txo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "outpoint":
			if in.IsNull() {
				in.Skip()
				out.Outpoint = nil
			} else {
				if out.Outpoint == nil {
					out.Outpoint = new(Outpoint)
				}
				if in.IsNull() {
					in.Skip()
					*out.Outpoint = nil
				} else {
					*out.Outpoint = in.Bytes()
				}
			}
		case "sats":
			out.Satoshis = uint64(in.Uint64())
		case "lock":
			if in.IsNull() {
				in.Skip()
				out.Lock = nil
			} else {
				out.Lock = in.Bytes()
			}
		case "Script":
			if in.IsNull() {
				in.Skip()
				out.Script = nil
			} else {
				if out.Script == nil {
					out.Script = new(bscript.Script)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Script).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE910b2f5EncodeGithubComFyxgamingVmLib4(out *jwriter.Writer, in Txo) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Outpoint != nil {
		const prefix string = ",\"outpoint\":"
		first = false
		out.RawString(prefix[1:])
		out.Base64Bytes(*in.Outpoint)
	}
	{
		const prefix string = ",\"sats\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Uint64(uint64(in.Satoshis))
	}
	{
		const prefix string = ",\"lock\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Lock)
	}
	{
		const prefix string = ",\"Script\":"
		out.RawString(prefix)
		if in.Script == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.Script).MarshalJSON())
		}
	}
	out.RawByte('}')
}
